<?php
/**
* English file for plugin codemirror
*
* @package wolf
* @subpackage codemirror
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast <djgprv@gmail.com>
*
**/
return array(
/** CodemirrorController.php */ 
'plugin settings saved.' => 'plugin settings saved.', 
'plugin settings not saved!' => 'plugin settings not saved!', 
/** index.php */ 
'CodeMirror syntax highlighter' => 'CodeMirror syntax highlighter', 
'Provides syntax highlighter using CodeMirror for backend.' => 'Provides syntax highlighter using CodeMirror for backend.', 
/** views/settings.php */ 
'Settings' => 'Settings', 
'Integrate:' => 'Integrate:', 
'Integrate with <strong>File Manager</strong> plugin.' => 'Integrate with <strong>File Manager</strong> plugin.', 
'Save' => 'Save', 
/** views/sidebar.php */ 
'CodeMirror Syntax Highlighter' => 'CodeMirror Syntax Highlighter', 
);